// userConstants.js

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SET_INSTRUCTOR = 'USER_SET_INSTRUCTOR';
export const USER_SET_STUDENT = 'USER_SET_STUDENT';
export const USER_SET_ROLE_FAIL = 'USER_SET_ROLE_FAIL';

//change password
export const USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_FAIL = 'USER_CHANGE_PASSWORD_FAIL';

// email pass shit
export const USER_CONFIRM_CHANGE_PASSWORD_REQUEST = 'USER_CONFIRM_CHANGE_PASSWORD_REQUEST';
export const USER_CONFIRM_CHANGE_PASSWORD_SUCCESS = 'USER_CONFIRM_CHANGE_PASSWORD_SUCCESS';
export const USER_CONFIRM_CHANGE_PASSWORD_FAIL = 'USER_CONFIRM_CHANGE_PASSWORD_FAIL';

// send email (email mismo) pass reset
export const USER_REQUEST_RESET_PASSWORD_REQUEST = 'USER_REQUEST_RESET_PASSWORD_REQUEST';
export const USER_REQUEST_RESET_PASSWORD_SUCCESS = 'USER_REQUEST_RESET_PASSWORD_SUCCESS';
export const USER_REQUEST_RESET_PASSWORD_FAIL = 'USER_REQUEST_RESET_PASSWORD_FAIL';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

// export const USER_VERIFY_OTP_REQUEST = 'USER_VERIFY_OTP_REQUEST';
// export const USER_VERIRIFY_OTP_SUCCESS = 'USER_VERIRIFY_OTP_SUCCESS';
// export const USER_VERIFY_OTP_FAIL = 'USER_VERIFY_OTP_FAIL';