# Generated by Django 4.2.10 on 2024-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_video_alter_product_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='editedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
